### PR TITLE
add css autoprefixer

### PR DESCRIPTION
**Pull request by veksen**

### CODE REVIEW

**Comment by jdalton** [comment]
Oh snao it's handled by cssnano. Nice!

**Comment by jdalton** [comment]
You [went digging](https://github.com/ben-eb/cssnano/blob/0c0405609ce683e2ea5605ccb5349fc9c784b84d/src/index.js#L88-L98) for this :D

**Comment by veksen** [comment]
Yep! The browsers could be tweaked, but I offered safe defaults.

**Comment by jdalton** [comment]
Ya I'll likely drop the Firefox callout since it's evergreen, but wow this was easier than I thought.

Thank you!

**Comment by jdalton** [comment]
Oh @veksen! Would you please sign the new [JS Foundation CLA](https://js.foundation/CLA/#you-certify-that)?

**Comment by veksen** [comment]
Oh, I just did, was the commit properly tagged with my name and email?

**Comment by jdalton** [comment]
No worries. The jQuery Foundation became the JS Foundation (under the Linux Foundation) so CLAs needed to be resigned.

**Comment by veksen** [comment]
Alright perfect!

**Pull request merged**
