### PR TITLE
added #hash jump on back/fwd history event [time 05:29]

### PR DESCRIPTION
**Pull request by sfinktah**
Just a few lines:

```
    // Jump to correct section on history change (back/forward button)
    window.addEventListener("hashchange", function(ev) {
        var elem, target;
        // target = ev.target.location.hash.substr(1);
        elem = document.getElementById(location.hash.substr(1));
        if (elem && elem.scrollIntoView) {
            elem.scrollIntoView();
        }
    });
```

### CODE REVIEW

**Comment by jdalton** [comment]
Ping @sfinktah.

**Comment by sfinktah** [comment]
signed, why closed for?

**Comment by jdalton** [comment]
Thanks @sfinktah!

Sorry about that. With the lag in response I assumed it was a drive-by PR so I tackled the issue.
If you signed you'll be all set for next time!

**Comment by sfinktah** [comment]
cool.

a better question might have been, why is this PR required anyway... wierdly underscore.js doesn't do any special handling for #hash and forward/backward work fine (jumping to the previous/next next section).

wierd.

**Comment by jdalton** [comment]
> a better question might have been, why is this PR required anyway

I'm not sure either, but I dig getting a chance to rely on `hashchange` 🙌

**Comment by sfinktah** [comment]
I'm not sure my sarcasm detector is fully operative.

Anyway, the site appears to be working as it should now, (tested in IE, Chrome, and Safari), so either you did something, or I was high on crack when I lodged that PR.

Afraid to reload unless it jumps again to 17.04 :p

**Pull request closed without merging**
