### PR TITLE
More subtle punctuation in docs menu

### LINKED ISSUE #133: Feature request: Reduce visual noise in docs
Whenever I take a look at the docs I struggle to properly keep track of the list of methods. I came to the conclusion that this is probably due to the noise of the `_.` on the left of every method.

I think it'd be a lot more convenient to have those two characters a little bit faded out. I've done this locally with some JavaScript and it's way nicer for my eyes (40% opacity).

What do you think?

### PR DESCRIPTION
**Pull request by Loilo**
Fixes #133.

### CODE REVIEW

**Comment by jdalton** [comment]
Ok, 🤖 is almost happy. Let's squash the commits to a single one so the `--reset-author` will fix just the one.

```
git rebase -i HEAD~4
```
Then you will see a list of commits with little `edit <hash> <description>` next to them.
In vim or other git assigned editor edit the line of subsequent commits and change `edit` to `s`. (In vim going in edit mode is `Esc` then `i`) then save (In vim `Esc` then `:x` then press `Enter`).

If it's too wonky or things blow up no worries I can clean it up on my end but I figure there's no time like today to practice rebasing 🐱

**Comment by Loilo** [comment]
Mh, why am I supposed to rebase `HEAD~4` when I've only got made two commits?

**Comment by jdalton** [comment]
Ah the ~4 just gives a list of 4 it won't actually rewire ones you don't touch but it just gives a nice like where you are where you're from view (a little padding).

**Comment by Loilo** [comment]
Ah, nice. Got me a bit worried that it showed foreign commits in the message in vim. ^_^

**Comment by jdalton** [comment]
Sometimes when I want to edit a few I'll just do `HEAD~10` just to get a list kicked off.

**Comment by Loilo** [comment]
Apparently I have rebased with the wrong user again. Wait a second. I got this.

**Comment by Loilo** [comment]
Okay, this didn't exactly work out. Let me recap:

* I need to rebase the done commits (4 by now caused by the several misuses)
* Then I need to somehow get rid of the old author with a commit using `--reset-author`? After rebasing git doesn't ask me to commit. So where to use that?
* By now I've consumed more of your time than by simply letting you change the menu items. 🙈

**Comment by jdalton** [comment]
Here's a gif!

**Comment by Loilo** [comment]
Sorry, I don't get it to work. I did exactly what your gif suggested (already did that last time) but this doesn't remove the wrong contributor from the commit history.

Also I added the other email to my github account (which I wanted to do anyway) but 🤖 is still not appreciating it...

**Comment by Loilo** [comment]
Thanks very much for your patience and effort. ❤️

**Comment by jdalton** [comment]
No worries. It's all fixed in our master branch now 😃

**Comment by Loilo** [comment]
Aand I'll need to append a small fix. My changes made a `_.` of the chaining function `_`.

**Comment by jdalton** [comment]
You'll want to create a new branch based off our latest master to avoid mucked up PR.

**Comment by Loilo** [comment]
Yep, I did so. I'll attach a new PR in a second.

**Pull request merged**
